### ISSUE TITLE
Improve the game

### ISSUE THREAD

**Issue by nasivuela** [Adalab/f-m2-evaluacion-intermedia-patrozada#1]
Super well done @patrozada  !!!

Here you have some tips to improve the exercise:

- [x] Move the feedback logic to a function an execute it on each click
- [x] Move you counter logic into a function and execute it on each click
- [x] You are writing many times "clueEl.innerHTML = 'something';", what about making a function that accepts a string as param and paints it into 'clueEl'?
- [x] Move variables and constants declarations to the top of the file
- [x] Remove commented code
- [x] Use a `label` to define the content of the input

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

Let me know if you have any doubts ;)

Go for it!!

**Comment by patrozada** [comment]
Thanks for your feedback @nasivuela! My handler looks so much clearer now :)
I have improved the exercise after your suggestions, now I'm ready to start working on its appearance.
Let me know if I need to fix anything else!

**Comment by nasivuela** [comment]
Sweet!!

![](https://media.giphy.com/media/jaGhFLgX9z916/giphy.gif)
